
import React, { useState } from 'react';
import { BookOpen, Sparkles, Send, Loader2, ArrowLeft } from 'lucide-react';
import { generateDietPlan } from '../geminiService';
import { UserProfile } from '../types';

interface DietPlanGeneratorProps {
  profile: UserProfile;
  onBack: () => void;
}

const DietPlanGenerator: React.FC<DietPlanGeneratorProps> = ({ profile, onBack }) => {
  const [plan, setPlan] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const result = await generateDietPlan(profile);
      setPlan(result);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500 pb-10">
      <section className="text-center space-y-4">
        <div className="w-20 h-20 bg-emerald-500 text-white rounded-3xl flex items-center justify-center mx-auto shadow-lg shadow-emerald-500/20">
            <Sparkles size={40} />
        </div>
        <h2 className="text-2xl font-bold">AI Diet Planner</h2>
        <p className="text-zinc-500 text-sm px-8">Get a 7-day nutritional blueprint tailored to your {profile.goal} goal.</p>
      </section>

      {!plan ? (
        <div className="bg-white dark:bg-zinc-900 rounded-3xl p-8 border border-zinc-100 dark:border-zinc-800 shadow-sm text-center space-y-6">
            <div className="space-y-2">
                <h4 className="font-bold">Plan Details</h4>
                <div className="flex flex-wrap gap-2 justify-center">
                    <Tag label={`${profile.goal}`} />
                    <Tag label={`${profile.weight}kg`} />
                    <Tag label="7 Days" />
                    <Tag label="Personalized" />
                </div>
            </div>
            <button 
                onClick={handleGenerate}
                disabled={loading}
                className="w-full flex items-center justify-center gap-2 py-4 bg-emerald-500 hover:bg-emerald-600 disabled:bg-emerald-300 text-white rounded-2xl font-bold transition-all active:scale-95"
            >
                {loading ? <Loader2 className="animate-spin" size={20} /> : <BookOpen size={20} />}
                {loading ? 'Generating Your Plan...' : 'Generate 7-Day Plan'}
            </button>
        </div>
      ) : (
        <div className="space-y-6">
            <div className="bg-white dark:bg-zinc-900 rounded-3xl p-6 border border-zinc-100 dark:border-zinc-800 shadow-sm prose dark:prose-invert prose-emerald max-w-none">
                <div className="whitespace-pre-wrap text-sm leading-relaxed">
                    {plan}
                </div>
            </div>
            <button onClick={() => setPlan(null)} className="w-full py-4 bg-zinc-100 dark:bg-zinc-800 rounded-2xl font-bold transition-all active:scale-95">
                Regenerate Plan
            </button>
        </div>
      )}

      <div className="p-6 bg-zinc-50 dark:bg-zinc-900/50 rounded-3xl border border-zinc-100 dark:border-zinc-800 space-y-3">
          <h4 className="font-bold text-sm">Health Disclaimer</h4>
          <p className="text-[10px] text-zinc-400 leading-normal">
              This plan is generated by AI and is intended for informational purposes only. Always consult with a registered dietitian or medical professional before starting a new diet or exercise regimen.
          </p>
      </div>
    </div>
  );
};

const Tag = ({ label }: { label: string }) => (
    <span className="text-[10px] font-bold px-3 py-1 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 rounded-full">{label}</span>
);

export default DietPlanGenerator;
